//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telcel.R9.Estructura.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int EmpleadoID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> PuestoID { get; set; }
        public Nullable<int> DepartamentoID { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
